# Generated by Django 5.2.1 on 2025-06-09 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('bio', models.TextField()),
                ('country', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('work_environment', models.JSONField(default=list)),
                ('challenges', models.JSONField(default=list)),
                ('code', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='company_name',
        ),
        migrations.AddField(
            model_name='user',
            name='mood',
            field=models.CharField(choices=[('happy', 'Happy'), ('neutral', 'Neutral'), ('sad', 'Sad'), ('angry', 'Angry'), ('anxious', 'Anxious'), ('tired', 'Tired'), ('confused', 'Confused')], default='neutral', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='company',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.company'),
        ),
    ]
