# Generated by Django 5.2.1 on 2025-06-06 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'ADMIN'), ('manager', 'MANAGER'), ('employee', 'EMPLOYEE'), ('therapist', 'THERAPIST')], default='EMPLOYEE', max_length=20),
        ),
    ]
