# Generated by Django 5.2.1 on 2025-06-09 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_company_remove_user_company_name_user_mood_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='num_of_employees',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
