# Generated by Django 5.2.1 on 2025-06-09 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user_image_user_is_anonymous_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='bio',
            field=models.TextField(blank=True),
        ),
    ]
