# Generated by Django 5.2.1 on 2025-06-10 03:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_guide_description_alter_webinar_option'),
    ]

    operations = [
        migrations.CreateModel(
            name='Affirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.TextField()),
                ('by', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Scene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('file', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Sound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('tag', models.CharField(max_length=10)),
                ('picture', models.FileField(upload_to='')),
                ('audio', models.FileField(upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='webinar',
            name='company',
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('option', models.CharField(choices=[('podcast', 'Podcast'), ('webinar', 'Webinar'), ('audio', 'Audio'), ('guide', 'Guide')], default='webinar', max_length=30)),
                ('by', models.CharField(blank=True, max_length=50)),
                ('date', models.DateTimeField()),
                ('description', models.TextField(blank=True, default='')),
                ('file', models.FileField(blank=True, default=None, null=True, upload_to='')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company')),
            ],
        ),
        migrations.DeleteModel(
            name='Guide',
        ),
        migrations.DeleteModel(
            name='Webinar',
        ),
    ]
