# Generated by Django 5.2.1 on 2025-06-12 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_role'),
        ('core', '0011_user_bio_user_rating_user_title'),
    ]

    operations = [
    ]
