# Generated by Django 5.2.1 on 2025-06-10 03:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mental_health', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='programenrollment',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='programenrollment',
            name='program',
        ),
        migrations.RemoveField(
            model_name='programenrollment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='wellnessprogram',
            name='created_by',
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('date', models.DateTimeField()),
                ('sent_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mental_health.therapistsession')),
            ],
        ),
        migrations.DeleteModel(
            name='MoodCheckIn',
        ),
        migrations.DeleteModel(
            name='ProgramEnrollment',
        ),
        migrations.DeleteModel(
            name='WellnessProgram',
        ),
    ]
