# Generated by Django 5.2.1 on 2025-06-11 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mental_health', '0002_alter_programenrollment_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='therapistsession',
            old_name='notes',
            new_name='message',
        ),
        migrations.AddField(
            model_name='therapistsession',
            name='from_therapist',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='ChatMessage',
        ),
    ]
