# Generated by Django 5.2.1 on 2025-06-11 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mental_health', '0004_rename_message_therapistsession_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='therapistsession',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
