# Generated by Django 5.2.1 on 2025-06-11 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mental_health', '0005_alter_chatmessage_date_alter_therapistsession_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='sent_by',
        ),
    ]
